config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  default_scope -> { order(id: :desc) }

  # # validating this way may cause TypeError: can't cast ItemUploader
  # # Soln: Field cannot be unique.. CarrierWave stores "no file" as empty string
  # validates_presence_of :name, :description, :file
  # validates :name, presence: true,
  #                  uniqueness: { case_sensitive: false }
  # validates :description, presence: true,
  #                         uniqueness: { case_sensitive: false }
  # validates :file, presence: true,
  #                  uniqueness: { case_sensitive: false }


  mount_uploader :file, ItemUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @item = Item.new
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    if @item.save
      # flash[:notice] = "Item was successfully created."
      respond_to :html, :js
    else
      render 'new'
    end
  end

  def update
    @item.remote_file_url ||= @item.remote_file_url
    if @item.update_attributes(item_params)
      # flash[:notice] = "Item was successfully updated."
      respond_to :html, :js
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    # flash[:notice] = "Item successfully deleted."
    respond_to :html, :js
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description, :remote_file_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :file %>
    <%= f.text_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<!-- for adding new item and updating -->
<div class="col-md-4 text-center" id="item_<%= item.id %>">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title"><%= item.name %></h3>
      <p><%= item.description.capitalize %></p>
      <hr>
      <h6 class="time_stamp"><%= time_ago_in_words(item.created_at) %></h6>
    </div>
    <div class="panel-body">
      <div>
        <%= image_tag item.file_url(:thumb) if item.file? %>
      </div>
      <br>
      <div class="btn-group" role="group" aria-label="...">
        <!-- button trigger modal -->
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#update_item_<%= item.id %>">
        Edit
        </button>
        <%= link_to "Delete", item, method: :delete, data: { confirm: "Are you sure?" }, remote: true, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
  <!-- modal for update action -->
  <%= form_for(item, method: :put, html: { multipart: true }, remote: true) do |f| %>
    <div class="modal fade" id="update_item_<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Edit item</h4>
          </div>
          <div class="modal-body">
            <div class="field">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="field">
              <%= f.label :description %>
              <%= f.text_area :description, rows: 3, class: "form-control" %>
            </div>
            <div class="field">
              <p><label>Current file<label></p>
              <p><%= image_tag(item.file) if item.file?%></p>
              <%= f.label :remote_file_url, "File URL" %>
              <%= f.text_field :remote_file_url, class: "form-control" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Update", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/items/create.js.erb
$('#create_item').modal('hide');
$('.item_name').val('');
$('.item_description').val('');
$('.item_url').val('');

$('#all_items').prepend('<%= j render @item %>');
$('#item_<%= @item.id %>').hide().fadeIn(500);

app/views/items/destroy.js.erb
$('#item_<%= @item.id %>').fadeOut(500, function(){
  $(this).remove();
});

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">
      <!-- button trigger modal -->
      <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#create_item">
        New item
      </button>
    </div>
  </div>
  <br>
  <hr>
  <div class="row" id="all_items">
    <%= render @items %>
  </div>
  <!-- modal for create action -->
  <%= form_for(@item, html: { multipart: true }, remote: true) do |f| %>
    <div class="modal fade" id="create_item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">New item</h4>
          </div>
          <div class="modal-body">
            <div class="field">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control item_name" %>
            </div>
            <div class="field">
              <%= f.label :description %>
              <%= f.text_area :description, rows: 3, class: "form-control item_description" %>
            </div>
            <div class="field">
              <%= f.label :file, "File URL" %>
              <%= image_tag(@item.file_url) if @item.file? %>
              <%= f.text_field :remote_file_url, class: "form-control item_url" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Create", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>File:</strong>
  <%= @item.file %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/update.js.erb
$('#update_item_<%= @item.id %>').modal('hide');
$('#item_<%= @item.id %>').fadeOut(500, function(){
  $(this).remove();
  $('#all_items').prepend('<%= j render @item %>')
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TryAjax1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>